apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-task-platform-staging

resources:
  - ../../base

patches:
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: worker-patch.yaml
    target:
      kind: Deployment
      name: worker
  - path: worker-hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: worker
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: ai-task-platform
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: backend-config
  - path: backend-secret-patch.yaml
    target:
      kind: Secret
      name: backend-secret

images:
  - name: docker.io/vignesh0756/ai-task-backend
    newTag: staging
  - name: docker.io/vignesh0756/ai-task-frontend
    newTag: staging
  - name: docker.io/vignesh0756/ai-task-worker
    newTag: staging
