apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - worker-configmap.yaml
  - mongo-statefulset.yaml
  - redis-statefulset.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - worker-deployment.yaml
  - worker-hpa.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: ai-task-platform
      app.kubernetes.io/managed-by: kustomize
